HEIGHT = 10
WIDTH = 10
TRANSFORMER_BATCH_SIZE = 5
NUMBER_OF_SOURCES = 5
NUMBER_OF_TARGETS = 5
NUMBER_OF_THREADS = 10
# min LNS batch size is 51
LNS_BATCH_SIZE = 5
MIN_PATH_LENGTH = WIDTH
MAX_PATH_LENGTH = WIDTH*10
NUMBER_OF_TRAINING_BATCHES = 10
MAX_LNS_RUN_TIME = 100
LNS_RESULT_PATHS_FILE = 'lns_result_paths.csv'
MAP_FILE = 'random-10-10-10.map'
LNS_OUTPUT_DIRECTORY = 'lns_outputs'
LNS_REQUESTS_DIRECTORY = 'lns_inputs'
