HEIGHT = 10
WIDTH = 10
TRANSFORMER_BATCH_SIZE = 8
NUMBER_OF_SOURCES = 5
NUMBER_OF_TARGETS = 5
NUMBER_OF_THREADS = 10
# min LNS batch size is 51
LNS_BATCH_SIZE = 51
MIN_PATH_LENGTH = WIDTH*2
MAX_PATH_LENGTH = WIDTH*10
NUMBER_OF_TRAINING_BATCHES = 10
MAX_LNS_RUN_TIME = 10000
LNS_RESULT_PATHS_FILE = 'lns_result_paths.csv'
MAP_FILE = 'random-10-10-10.map'
LNS_OUTPUT_DIRECTORY = 'lns_outputs'
LNS_REQUESTS_DIRECTORY = 'lns_inputs'
